name: Cloudflare

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Crawl ]
    types: [ completed ]

jobs:
  push-to-kv:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 1

      - name: Install wrangler
        run: npm install --global wrangler

      - name: Push data to KV and trigger weekly digest
        working-directory: worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          wrangler kv key put --remote --binding=KV publications  --path=../output/publications.json
          wrangler kv key put --remote --binding=KV preprints     --path=../output/preprints.json
          wrangler kv key put --remote --binding=KV journals      --path=../parameters/journals.json
          wrangler kv key put --remote --binding=KV osf_subjects  --path=../parameters/osf_subjects.json
          wrangler workflows trigger weekly-digest
